def app_intro():
    return """
    <div style='text-align: left; padding: 20px; border-radius: 10px;'>
    <h1 style='text-align: center; color: #333;'>📊 NaturalViz: NLP-Driven Data Visualization 🚀</h1>
    <h2 style='text-align: center; color: #666;'>Hackathon Entry for CANIS Data Visualization and Foreign Interferences</h2>
            
    <p style='font-size: 18px; color: #444;'>Welcome to NaturalViz, an experimental foray into leveraging Language Models (LLMs) for data exploration and visualization. This app is our entry for the CANIS Data Visualization and Foreign Interference hackathon, showcasing the cutting-edge intersection of natural language understanding and data analytics.</p>

    <h3 style='color: #777;'>Innovative Approach:</h3>
    <p style='font-size: 16px; color: #555;'><b>NLP-Driven Visualization:</b> Our application pioneers a novel approach, employing advanced Language Models to translate natural language queries into executable Python code. Witness the seamless generation of insightful visualizations tailored to complex inquiries, exemplifying the potential of LLMs in the field of data visualization.</p>
    
    <p style='font-size: 16px; color: #555;'><b>Data Exploration Chatbot:</b> Engage with our chatbot designed exclusively for data exploration. Pose questions, request visualizations, and navigate the diverse landscape of data insights with the assistance of natural language interactions.</p>

    <h3 style='color: #777;'>Academic Exploration:</h3>
    <p style='font-size: 16px; color: #555;'>This experimental approach reflects our commitment to exploring the evolving landscape of Language Models in the context of data analytics. By fusing natural language capabilities with data visualization, we aim to push the boundaries of innovation in this rapidly advancing field.</p>

    <h3 style='color: #777;'>Get Started:</h3>
    <p style='font-size: 16px; color: #555;'>Embark on the NLP-driven data visualization journey by entering your queries in natural language. Switch to the chatbot tab to interact with our conversational AI and uncover hidden patterns in the data. The CANIS hackathon provides a platform for showcasing the experimental and academic dimensions of our innovative approach to data exploration and visualization.</p>
    </div>
    """

def how_use_intro():
    return """
    <div style='text-align: left; padding: 20px; border-radius: 10px;'>
    <h2 style='text-align: center; color: #333;'>Unlock Insights with NaturalViz! 🌐🔍</h2>
    <br>
    <h3 style='color: #777;'>How to Use:</h3>
    <ul style='font-size: 16px; color: #555;'>
    <li><b>NLP-Driven Visualization:</b> Head to the first tab to explore NLP-driven data visualizations. Enter your queries in natural language, click "Submit," and witness dynamic and personalized visual insights generated by the power of Language Models.</li>
    <li><b>Data Exploration Chatbot:</b> In the second tab, engage with our chatbot. Ask questions about the dataset, request specific visualizations, and let the chatbot guide you through the exploration process using the latest advancements in natural language understanding.</li>
    <li><b>Code and Analysis:</b> Delve into the generated code and analysis in the dedicated code section for the NLP-driven visualization. Gain insights into the methodology and technical prowess behind the visualizations, showcasing the experimental nature of our approach.</li>
    </ul>
    <br>
    </div>
"""
